server:
  port: 8090
  servlet:
    context-path: /spring
  error:
    whitelabel.enabled: true
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-stacktrace: always

logging:
  level:
    web: DEBUG
    fr: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true
  datasource:
    url: jdbc:mysql://mysql-cestquoiunpc.alwaysdata.net:3306/cestquoiunpc_sql
    username: 251284
    password: ndi45100
    driver-class-name: org.mariadb.jdbc.Driver
